# Generated by Django 3.2.7 on 2024-03-07 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='regtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=150)),
                ('Gender', models.CharField(max_length=150)),
                ('Dob', models.CharField(max_length=150)),
                ('Aadhar', models.CharField(max_length=150)),
                ('Weapon', models.CharField(max_length=150)),
                ('Email', models.CharField(max_length=150)),
                ('Mobile', models.CharField(max_length=150)),
                ('Blood_group', models.CharField(max_length=150)),
                ('Height', models.CharField(max_length=150)),
                ('Weight', models.CharField(max_length=150)),
                ('Fencer_category', models.CharField(max_length=150)),
                ('District', models.CharField(max_length=150)),
                ('Father_name', models.CharField(max_length=150)),
                ('Mother_name', models.CharField(max_length=150)),
                ('Mobile_No', models.CharField(max_length=150)),
                ('Pincode', models.CharField(max_length=150)),
                ('Address', models.CharField(max_length=150)),
                ('Landmark', models.CharField(max_length=150)),
                ('District_p', models.CharField(max_length=150)),
                ('State', models.CharField(max_length=150)),
                ('City', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('image', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='tournamenttable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('place', models.CharField(max_length=150)),
                ('start_date', models.DateField(max_length=150)),
                ('end_date', models.DateField(max_length=150)),
            ],
        ),
    ]
