# Generated by Django 3.2.7 on 2024-03-07 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fencing', '0003_alter_tournament_schedule_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament_schedule',
            name='status',
            field=models.CharField(max_length=150),
        ),
    ]
