# Generated by Django 3.2.7 on 2024-03-07 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fencing', '0004_alter_tournament_schedule_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='tournament_medals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=150)),
                ('gold', models.CharField(max_length=150)),
                ('silver', models.CharField(max_length=150)),
                ('bronze', models.CharField(max_length=150)),
                ('total', models.CharField(max_length=150)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fencing.tournamenttable')),
            ],
        ),
    ]
