# Generated by Django 3.2.7 on 2024-03-08 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fencing', '0006_auto_20240307_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='tournament_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=150)),
                ('date', models.DateField(max_length=150)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fencing.tournamenttable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fencing.regtable')),
            ],
        ),
    ]
