# Generated by Django 3.2.7 on 2024-03-11 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fencing', '0009_tournament_register_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='tournament_pools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant1', models.CharField(max_length=150)),
                ('participant2', models.CharField(max_length=150)),
                ('v', models.IntegerField()),
                ('m', models.IntegerField()),
                ('vm', models.IntegerField()),
                ('ts', models.IntegerField()),
                ('tr', models.IntegerField()),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fencing.tournamenttable')),
            ],
        ),
    ]
