# Generated by Django 3.2.7 on 2024-03-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fencing', '0010_tournament_pools'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament_pools',
            name='country',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
