# Generated by Django 3.2.7 on 2024-03-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fencing', '0011_tournament_pools_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament_pools',
            name='vm',
            field=models.FloatField(),
        ),
    ]
